### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by rrgks6221** [team-grass-farm/uncloudy-prometheus-exporter#4]
### server instance (NHN-Toast)
- cpu 2
- ram 2G

해당 서버에 배포

#### 전통적인 방식
해당 instance에 prometheus, nodejs를 각각 설치해 배포

#### 도커를 이용한 방식
해당 instance에 prometheus, nodejs를 도커를 이용하여 배포

두가지 방안 중 선택

**Comment by rrgks6221** [comment]
@100kimch @jnubugo 
배포 전략 의견 주세요

**Comment by jnubugo** [comment]
Server Instance 
CPU 2, Ram 2GB -> CPU 1, Ram 1GB 수정
.pem 접근키 동일, IP변경 
-> ssh -i prometheus-test.pem ubuntu@133.186.222.196

배포전략 - Instance에 직접 설치
(2회 이상 오류 발생시 Docker 방식으로 변경 - 타 서버 활용)
