### ISSUE TITLE
pod, node CPU, Memory, Disk 사용량 유사 범위 반영

### ISSUE THREAD

**Issue by 100kimch** [team-grass-farm/uncloudy-prometheus-exporter#9]

**Comment by rrgks6221** [comment]
@100kimch @jnubugo 
node_memory_usage_bytes, pod_memory_usage_bytes 의 값을 node, pod의 총 메모리 byte / node_memory_usage, pod_memory_usage로 하려 하는데 node, pod의 메모리 총량을 몇으로 잡으면 좋을까요???
ex) memory 4gb 기준
```ts
const nodeMemoryTotal: number = 4294967296 // 메모리 총량
const nodeMemoryUsage: number = 0.2 // 메모리 사용량
const nodeMemoryUsageBytes: number = 858993459 // 메모리 사용 바이트
```

**Comment by jnubugo** [comment]
Pod는 0.5GB(500mib) ~4GB
Node는 16GB, 32GB, 64GB, 128GB로 하면 적당할 것 같아

Pod는 10mib단위로 세분화해서 쓰기도 해서 랜덤하게 한다해도 괜찮고 Node는 비교적 고정해서 쓰니까 저 중 고르면 좋을것 같거

**Comment by rrgks6221** [comment]
우선은
node: 16GB
pad: 2GB
로 구현 해놓을게요
